"""
Django settings for dcrm project.
Generated by 'django-admin startproject' using Django 5.0.14.

Las variables sensibles (SECRET_KEY, base de datos, etc.) se cargan
desde el archivo .env usando python-dotenv para mantener la seguridad.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde el archivo .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ── Seguridad principal ────────────────────────────────────────────────────────
# SECRET_KEY se carga desde .env — nunca debe estar en el código fuente
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Hosts permitidos (vacío en desarrollo, requerido en producción)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcrm.wsgi.application'


# ── Base de datos (credenciales desde .env) ────────────────────────────────────
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':     os.environ.get('DB_NAME', 'clientee'),
        'USER':     os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST':     os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT':     os.environ.get('DB_PORT', '3306'),
    }
}

LOGIN_URL = 'home'

# ── Configuración de mensajes ──────────────────────────────────────────────────
# Mapea los niveles de mensajes de Django a clases CSS de Bootstrap
from django.contrib.messages import constants as messages_constants
MESSAGE_TAGS = {
    messages_constants.DEBUG:   'secondary',
    messages_constants.INFO:    'info',
    messages_constants.SUCCESS: 'success',
    messages_constants.WARNING: 'warning',
    messages_constants.ERROR:   'danger',
}


# ── Validación de contraseñas ──────────────────────────────────────────────────
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ── Internacionalización ───────────────────────────────────────────────────────
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True


# ── Archivos estáticos ─────────────────────────────────────────────────────────
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website', 'templates', 'static'),
]

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ════════════════════════════════════════════════════════════════════════════════
# SESIONES Y COOKIES SEGURAS
# Cumplen el criterio: "Sesiones y cookies seguras"
# ════════════════════════════════════════════════════════════════════════════════

# Cookie de sesión no accesible por JavaScript (previene XSS session hijacking)
SESSION_COOKIE_HTTPONLY = True

# Duración de sesión: 2 horas de inactividad
SESSION_COOKIE_AGE = 7200

# Renovar la sesión en cada request (reinicia el contador)
SESSION_SAVE_EVERY_REQUEST = True

# Cerrar sesión al cerrar el navegador (False = sesión persistente con edad definida)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Cookie de sesión solo viaja por HTTPS (se activa automáticamente en producción)
SESSION_COOKIE_SECURE = not DEBUG

# Token CSRF solo viaja por HTTPS en producción
CSRF_COOKIE_SECURE = not DEBUG

# Token CSRF no accesible por JavaScript
CSRF_COOKIE_HTTPONLY = True


# ════════════════════════════════════════════════════════════════════════════════
# CAPAS DE SEGURIDAD HTTPS Y HEADERS
# Cumplen el criterio: "HTTPS y capas de seguridad"
# ════════════════════════════════════════════════════════════════════════════════

# Previene ataques XSS reflejados (cabecera X-XSS-Protection)
SECURE_BROWSER_XSS_FILTER = True

# Previene MIME type sniffing (cabecera X-Content-Type-Options)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Previene clickjacking (cabecera X-Frame-Options: DENY)
X_FRAME_OPTIONS = 'DENY'

# Redirigir HTTP → HTTPS automáticamente en producción
SECURE_SSL_REDIRECT = not DEBUG

# HTTP Strict Transport Security (HSTS) — fuerza HTTPS por 1 año en producción
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG

# Proxy seguro (necesario si hay nginx/apache delante)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None
